Start the workflow tutorial
NCATSTranslator/TranslatorTechnicalDocumentation pull request #75
Opened 2024-09-10 18:26 UTC by dkoslicki

2024-09-10 18:30 UTC, nlharris approved these changes
It's a start!

2024-09-10 19:32 UTC, RichardBruskiewich approved these changes

2024-09-11 00:08 UTC, RichardBruskiewich requested changes
Hi David, please fix the <snip> tags in the file. I'm wondering if some content in the JSON was lost because of these.

2024-09-11 00:11 UTC, RichardBruskiewich approved these changes

2024-09-11 00:11 UTC, merged